// Code generated by ent, DO NOT EDIT.

package jobtaxonomy

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the jobtaxonomy type in the database.
	Label = "job_taxonomy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldTaxonomyID holds the string denoting the taxonomy_id field in the database.
	FieldTaxonomyID = "taxonomy_id"
	// Table holds the table name of the jobtaxonomy in the database.
	Table = "job_taxonomies"
)

// Columns holds all SQL columns for jobtaxonomy fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldTaxonomyID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the JobTaxonomy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByTaxonomyID orders the results by the taxonomy_id field.
func ByTaxonomyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxonomyID, opts...).ToFunc()
}
