// Code generated by ent, DO NOT EDIT.

package jobtaxonomy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldJobID, v))
}

// TaxonomyID applies equality check predicate on the "taxonomy_id" field. It's identical to TaxonomyIDEQ.
func TaxonomyID(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldTaxonomyID, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLTE(FieldJobID, v))
}

// TaxonomyIDEQ applies the EQ predicate on the "taxonomy_id" field.
func TaxonomyIDEQ(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldEQ(FieldTaxonomyID, v))
}

// TaxonomyIDNEQ applies the NEQ predicate on the "taxonomy_id" field.
func TaxonomyIDNEQ(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNEQ(FieldTaxonomyID, v))
}

// TaxonomyIDIn applies the In predicate on the "taxonomy_id" field.
func TaxonomyIDIn(vs ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldIn(FieldTaxonomyID, vs...))
}

// TaxonomyIDNotIn applies the NotIn predicate on the "taxonomy_id" field.
func TaxonomyIDNotIn(vs ...int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldNotIn(FieldTaxonomyID, vs...))
}

// TaxonomyIDGT applies the GT predicate on the "taxonomy_id" field.
func TaxonomyIDGT(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGT(FieldTaxonomyID, v))
}

// TaxonomyIDGTE applies the GTE predicate on the "taxonomy_id" field.
func TaxonomyIDGTE(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldGTE(FieldTaxonomyID, v))
}

// TaxonomyIDLT applies the LT predicate on the "taxonomy_id" field.
func TaxonomyIDLT(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLT(FieldTaxonomyID, v))
}

// TaxonomyIDLTE applies the LTE predicate on the "taxonomy_id" field.
func TaxonomyIDLTE(v int) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(sql.FieldLTE(FieldTaxonomyID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JobTaxonomy) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JobTaxonomy) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JobTaxonomy) predicate.JobTaxonomy {
	return predicate.JobTaxonomy(func(s *sql.Selector) {
		p(s.Not())
	})
}
