// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/job"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetUpdatedAt sets the "updated_at" field.
func (ju *JobUpdate) SetUpdatedAt(t time.Time) *JobUpdate {
	ju.mutation.SetUpdatedAt(t)
	return ju
}

// SetTitle sets the "title" field.
func (ju *JobUpdate) SetTitle(s string) *JobUpdate {
	ju.mutation.SetTitle(s)
	return ju
}

// SetSlug sets the "slug" field.
func (ju *JobUpdate) SetSlug(s string) *JobUpdate {
	ju.mutation.SetSlug(s)
	return ju
}

// SetStatus sets the "status" field.
func (ju *JobUpdate) SetStatus(s string) *JobUpdate {
	ju.mutation.SetStatus(s)
	return ju
}

// SetApplyTo sets the "apply_to" field.
func (ju *JobUpdate) SetApplyTo(s string) *JobUpdate {
	ju.mutation.SetApplyTo(s)
	return ju
}

// SetDescription sets the "description" field.
func (ju *JobUpdate) SetDescription(s string) *JobUpdate {
	ju.mutation.SetDescription(s)
	return ju
}

// SetCompanyID sets the "company_id" field.
func (ju *JobUpdate) SetCompanyID(i int) *JobUpdate {
	ju.mutation.ResetCompanyID()
	ju.mutation.SetCompanyID(i)
	return ju
}

// AddCompanyID adds i to the "company_id" field.
func (ju *JobUpdate) AddCompanyID(i int) *JobUpdate {
	ju.mutation.AddCompanyID(i)
	return ju
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	if err := ju.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ju *JobUpdate) defaults() error {
	if _, ok := ju.mutation.UpdatedAt(); !ok {
		if job.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized job.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := job.UpdateDefaultUpdatedAt()
		ju.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ju.mutation.Title(); ok {
		_spec.SetField(job.FieldTitle, field.TypeString, value)
	}
	if value, ok := ju.mutation.Slug(); ok {
		_spec.SetField(job.FieldSlug, field.TypeString, value)
	}
	if value, ok := ju.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := ju.mutation.ApplyTo(); ok {
		_spec.SetField(job.FieldApplyTo, field.TypeString, value)
	}
	if value, ok := ju.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if value, ok := ju.mutation.CompanyID(); ok {
		_spec.SetField(job.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedCompanyID(); ok {
		_spec.AddField(job.FieldCompanyID, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (juo *JobUpdateOne) SetUpdatedAt(t time.Time) *JobUpdateOne {
	juo.mutation.SetUpdatedAt(t)
	return juo
}

// SetTitle sets the "title" field.
func (juo *JobUpdateOne) SetTitle(s string) *JobUpdateOne {
	juo.mutation.SetTitle(s)
	return juo
}

// SetSlug sets the "slug" field.
func (juo *JobUpdateOne) SetSlug(s string) *JobUpdateOne {
	juo.mutation.SetSlug(s)
	return juo
}

// SetStatus sets the "status" field.
func (juo *JobUpdateOne) SetStatus(s string) *JobUpdateOne {
	juo.mutation.SetStatus(s)
	return juo
}

// SetApplyTo sets the "apply_to" field.
func (juo *JobUpdateOne) SetApplyTo(s string) *JobUpdateOne {
	juo.mutation.SetApplyTo(s)
	return juo
}

// SetDescription sets the "description" field.
func (juo *JobUpdateOne) SetDescription(s string) *JobUpdateOne {
	juo.mutation.SetDescription(s)
	return juo
}

// SetCompanyID sets the "company_id" field.
func (juo *JobUpdateOne) SetCompanyID(i int) *JobUpdateOne {
	juo.mutation.ResetCompanyID()
	juo.mutation.SetCompanyID(i)
	return juo
}

// AddCompanyID adds i to the "company_id" field.
func (juo *JobUpdateOne) AddCompanyID(i int) *JobUpdateOne {
	juo.mutation.AddCompanyID(i)
	return juo
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	if err := juo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (juo *JobUpdateOne) defaults() error {
	if _, ok := juo.mutation.UpdatedAt(); !ok {
		if job.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized job.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := job.UpdateDefaultUpdatedAt()
		juo.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := juo.mutation.Title(); ok {
		_spec.SetField(job.FieldTitle, field.TypeString, value)
	}
	if value, ok := juo.mutation.Slug(); ok {
		_spec.SetField(job.FieldSlug, field.TypeString, value)
	}
	if value, ok := juo.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := juo.mutation.ApplyTo(); ok {
		_spec.SetField(job.FieldApplyTo, field.TypeString, value)
	}
	if value, ok := juo.mutation.Description(); ok {
		_spec.SetField(job.FieldDescription, field.TypeString, value)
	}
	if value, ok := juo.mutation.CompanyID(); ok {
		_spec.SetField(job.FieldCompanyID, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedCompanyID(); ok {
		_spec.AddField(job.FieldCompanyID, field.TypeInt, value)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
