// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/jobtaxonomy"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/predicate"
)

// JobTaxonomyQuery is the builder for querying JobTaxonomy entities.
type JobTaxonomyQuery struct {
	config
	ctx        *QueryContext
	order      []jobtaxonomy.OrderOption
	inters     []Interceptor
	predicates []predicate.JobTaxonomy
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobTaxonomyQuery builder.
func (jtq *JobTaxonomyQuery) Where(ps ...predicate.JobTaxonomy) *JobTaxonomyQuery {
	jtq.predicates = append(jtq.predicates, ps...)
	return jtq
}

// Limit the number of records to be returned by this query.
func (jtq *JobTaxonomyQuery) Limit(limit int) *JobTaxonomyQuery {
	jtq.ctx.Limit = &limit
	return jtq
}

// Offset to start from.
func (jtq *JobTaxonomyQuery) Offset(offset int) *JobTaxonomyQuery {
	jtq.ctx.Offset = &offset
	return jtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jtq *JobTaxonomyQuery) Unique(unique bool) *JobTaxonomyQuery {
	jtq.ctx.Unique = &unique
	return jtq
}

// Order specifies how the records should be ordered.
func (jtq *JobTaxonomyQuery) Order(o ...jobtaxonomy.OrderOption) *JobTaxonomyQuery {
	jtq.order = append(jtq.order, o...)
	return jtq
}

// First returns the first JobTaxonomy entity from the query.
// Returns a *NotFoundError when no JobTaxonomy was found.
func (jtq *JobTaxonomyQuery) First(ctx context.Context) (*JobTaxonomy, error) {
	nodes, err := jtq.Limit(1).All(setContextOp(ctx, jtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobtaxonomy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) FirstX(ctx context.Context) *JobTaxonomy {
	node, err := jtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobTaxonomy ID from the query.
// Returns a *NotFoundError when no JobTaxonomy ID was found.
func (jtq *JobTaxonomyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(1).IDs(setContextOp(ctx, jtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobtaxonomy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) FirstIDX(ctx context.Context) int {
	id, err := jtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobTaxonomy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JobTaxonomy entity is found.
// Returns a *NotFoundError when no JobTaxonomy entities are found.
func (jtq *JobTaxonomyQuery) Only(ctx context.Context) (*JobTaxonomy, error) {
	nodes, err := jtq.Limit(2).All(setContextOp(ctx, jtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobtaxonomy.Label}
	default:
		return nil, &NotSingularError{jobtaxonomy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) OnlyX(ctx context.Context) *JobTaxonomy {
	node, err := jtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobTaxonomy ID in the query.
// Returns a *NotSingularError when more than one JobTaxonomy ID is found.
// Returns a *NotFoundError when no entities are found.
func (jtq *JobTaxonomyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(2).IDs(setContextOp(ctx, jtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobtaxonomy.Label}
	default:
		err = &NotSingularError{jobtaxonomy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) OnlyIDX(ctx context.Context) int {
	id, err := jtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobTaxonomies.
func (jtq *JobTaxonomyQuery) All(ctx context.Context) ([]*JobTaxonomy, error) {
	ctx = setContextOp(ctx, jtq.ctx, "All")
	if err := jtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JobTaxonomy, *JobTaxonomyQuery]()
	return withInterceptors[[]*JobTaxonomy](ctx, jtq, qr, jtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) AllX(ctx context.Context) []*JobTaxonomy {
	nodes, err := jtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobTaxonomy IDs.
func (jtq *JobTaxonomyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if jtq.ctx.Unique == nil && jtq.path != nil {
		jtq.Unique(true)
	}
	ctx = setContextOp(ctx, jtq.ctx, "IDs")
	if err = jtq.Select(jobtaxonomy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) IDsX(ctx context.Context) []int {
	ids, err := jtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jtq *JobTaxonomyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jtq.ctx, "Count")
	if err := jtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jtq, querierCount[*JobTaxonomyQuery](), jtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) CountX(ctx context.Context) int {
	count, err := jtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jtq *JobTaxonomyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jtq.ctx, "Exist")
	switch _, err := jtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jtq *JobTaxonomyQuery) ExistX(ctx context.Context) bool {
	exist, err := jtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobTaxonomyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jtq *JobTaxonomyQuery) Clone() *JobTaxonomyQuery {
	if jtq == nil {
		return nil
	}
	return &JobTaxonomyQuery{
		config:     jtq.config,
		ctx:        jtq.ctx.Clone(),
		order:      append([]jobtaxonomy.OrderOption{}, jtq.order...),
		inters:     append([]Interceptor{}, jtq.inters...),
		predicates: append([]predicate.JobTaxonomy{}, jtq.predicates...),
		// clone intermediate query.
		sql:  jtq.sql.Clone(),
		path: jtq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		JobID int `json:"job_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobTaxonomy.Query().
//		GroupBy(jobtaxonomy.FieldJobID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jtq *JobTaxonomyQuery) GroupBy(field string, fields ...string) *JobTaxonomyGroupBy {
	jtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JobTaxonomyGroupBy{build: jtq}
	grbuild.flds = &jtq.ctx.Fields
	grbuild.label = jobtaxonomy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		JobID int `json:"job_id,omitempty"`
//	}
//
//	client.JobTaxonomy.Query().
//		Select(jobtaxonomy.FieldJobID).
//		Scan(ctx, &v)
func (jtq *JobTaxonomyQuery) Select(fields ...string) *JobTaxonomySelect {
	jtq.ctx.Fields = append(jtq.ctx.Fields, fields...)
	sbuild := &JobTaxonomySelect{JobTaxonomyQuery: jtq}
	sbuild.label = jobtaxonomy.Label
	sbuild.flds, sbuild.scan = &jtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JobTaxonomySelect configured with the given aggregations.
func (jtq *JobTaxonomyQuery) Aggregate(fns ...AggregateFunc) *JobTaxonomySelect {
	return jtq.Select().Aggregate(fns...)
}

func (jtq *JobTaxonomyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jtq); err != nil {
				return err
			}
		}
	}
	for _, f := range jtq.ctx.Fields {
		if !jobtaxonomy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jtq.path != nil {
		prev, err := jtq.path(ctx)
		if err != nil {
			return err
		}
		jtq.sql = prev
	}
	return nil
}

func (jtq *JobTaxonomyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JobTaxonomy, error) {
	var (
		nodes = []*JobTaxonomy{}
		_spec = jtq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JobTaxonomy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JobTaxonomy{config: jtq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (jtq *JobTaxonomyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jtq.querySpec()
	_spec.Node.Columns = jtq.ctx.Fields
	if len(jtq.ctx.Fields) > 0 {
		_spec.Unique = jtq.ctx.Unique != nil && *jtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jtq.driver, _spec)
}

func (jtq *JobTaxonomyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jobtaxonomy.Table, jobtaxonomy.Columns, sqlgraph.NewFieldSpec(jobtaxonomy.FieldID, field.TypeInt))
	_spec.From = jtq.sql
	if unique := jtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jtq.path != nil {
		_spec.Unique = true
	}
	if fields := jtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobtaxonomy.FieldID)
		for i := range fields {
			if fields[i] != jobtaxonomy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jtq *JobTaxonomyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jtq.driver.Dialect())
	t1 := builder.Table(jobtaxonomy.Table)
	columns := jtq.ctx.Fields
	if len(columns) == 0 {
		columns = jobtaxonomy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jtq.sql != nil {
		selector = jtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jtq.ctx.Unique != nil && *jtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jtq.predicates {
		p(selector)
	}
	for _, p := range jtq.order {
		p(selector)
	}
	if offset := jtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobTaxonomyGroupBy is the group-by builder for JobTaxonomy entities.
type JobTaxonomyGroupBy struct {
	selector
	build *JobTaxonomyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jtgb *JobTaxonomyGroupBy) Aggregate(fns ...AggregateFunc) *JobTaxonomyGroupBy {
	jtgb.fns = append(jtgb.fns, fns...)
	return jtgb
}

// Scan applies the selector query and scans the result into the given value.
func (jtgb *JobTaxonomyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jtgb.build.ctx, "GroupBy")
	if err := jtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobTaxonomyQuery, *JobTaxonomyGroupBy](ctx, jtgb.build, jtgb, jtgb.build.inters, v)
}

func (jtgb *JobTaxonomyGroupBy) sqlScan(ctx context.Context, root *JobTaxonomyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jtgb.fns))
	for _, fn := range jtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jtgb.flds)+len(jtgb.fns))
		for _, f := range *jtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JobTaxonomySelect is the builder for selecting fields of JobTaxonomy entities.
type JobTaxonomySelect struct {
	*JobTaxonomyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jts *JobTaxonomySelect) Aggregate(fns ...AggregateFunc) *JobTaxonomySelect {
	jts.fns = append(jts.fns, fns...)
	return jts
}

// Scan applies the selector query and scans the result into the given value.
func (jts *JobTaxonomySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jts.ctx, "Select")
	if err := jts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JobTaxonomyQuery, *JobTaxonomySelect](ctx, jts.JobTaxonomyQuery, jts, jts.inters, v)
}

func (jts *JobTaxonomySelect) sqlScan(ctx context.Context, root *JobTaxonomyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jts.fns))
	for _, fn := range jts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
