// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/toufiq-austcse/go-api-boilerplate/ent/schema"
	"github.com/toufiq-austcse/go-api-boilerplate/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTitle is the schema descriptor for title field.
	todoDescTitle := todoFields[1].Descriptor()
	// todo.DefaultTitle holds the default value on creation for the title field.
	todo.DefaultTitle = todoDescTitle.Default.(string)
	// todoDescStatus is the schema descriptor for status field.
	todoDescStatus := todoFields[2].Descriptor()
	// todo.DefaultStatus holds the default value on creation for the status field.
	todo.DefaultStatus = todoDescStatus.Default.(string)
}
