-- Create "companies" table
CREATE TABLE "companies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "location" character varying NULL, "logo_url" character varying NULL, "website_url" character varying NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "size" character varying NULL, "industry" character varying NULL, "established" character varying NULL, "description" character varying NULL, "culture_description" character varying NULL, "hiring_description" character varying NULL, PRIMARY KEY ("id"));
-- Create index "companies_email_key" to table: "companies"
CREATE UNIQUE INDEX "companies_email_key" ON "companies" ("email");
-- Create "job_taxonomies" table
CREATE TABLE "job_taxonomies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "job_id" bigint NOT NULL, "taxonomy_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "jobs" table
CREATE TABLE "jobs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "slug" character varying NOT NULL, "apply_to" character varying NOT NULL, "description" character varying NOT NULL, "company_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "taxonomies" table
CREATE TABLE "taxonomies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "parent_id" character varying NULL, "title" character varying NULL, "slug" character varying NULL, "type" character varying NULL, PRIMARY KEY ("id"));
