// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// JobTaxonomy is the predicate function for jobtaxonomy builders.
type JobTaxonomy func(*sql.Selector)

// Taxonomy is the predicate function for taxonomy builders.
type Taxonomy func(*sql.Selector)
